### ISSUE TITLE
Research work on boids, and related papers

### ISSUE THREAD

**Issue by AIMSIIITA** [AIMSIIITA/FLOCKING#2]
**Issue Description:**
We are compiling comprehensive research on Boids and the dynamics of their movement for our project. To ensure transparency and knowledge sharing within the team, we are initiating this request to collect and document all research work related to Boids, including the papers and sources that have been referenced or provided valuable insights.

**Additional Details:**
- **Objective:** Compile and document research work on Boids and their movement dynamics.
- **Requested Content:**
  - Summaries of research findings.
  - References to papers and sources.
  - Any understanding of Boids' movement principles.

**Instructions for Pushing Research:**
1. Fork the repository to your local environment.
2. Create a new branch specifically for Boids research work.
3. Push summaries, references, and any relevant information to the designated branch.
4. Clearly document your contributions to facilitate collaboration.

**Note:**
- Ensure that your contributions are well-documented for easy comprehension.
- If a paper or source is proprietary, provide a brief summary or key takeaways.

**Comment by DebjyotiRay** [comment]
Claim
